### PR TITLE
Added documentation for backing up, updating and restoring Taiga's docker installation

### PR DESCRIPTION
**Pull request by nuokh**
Hello everybody,

I want to deploy Taiga.io in a production environment using the Docker installation but before I can do so I need to make sure I can backup, update and restore it.

I am sure that I am not the only one in need of

- a clear step-by-step documentation describing backup, update & restore plus
- a simple, tested, low-complexity "one size fits all" way to backup Taiga's data. Be it zipped on ad-hoc basis, rsynced to a network share regularly using a cronjob or just saved to my workstations's desktop via FTP manually before the next big update in case something breaks.

I would like to share my work so everybody can get started quickly using Taiga's docker installation **and** is able to maintain the installation over the years without having to read through the Docker docs in their entirety.

This pull requests adds to the documentation explaining volume backup, the easy backup alternative introduced in my second pull request, updating Taiga's docker installation and describing some relevant docker basics along the way

My second pull-request adds all the groundwork to make simple backups possible by extending the Docker Compose files while still keeping the defaults compatible with the current default taiga-docker installation. It reduces the complexity for newcomers to apply the easier backup alternative by commenting the relevant parts out while following the associated step-by-step guide: https://github.com/kaleidos-ventures/taiga-docker/pull/10

I tested the added "easy alternative" backup and restore method multiple times to make sure it works.

I hope my pull request to add this for everybody will get accepted.

Feedback is, as always, very welcome!

### CODE REVIEW

**Comment by yamila-moreno** [comment]
Hi @nuokh thanks for your contributions! ✨ 

We've reviewed thoroughly both PRs and we've some insights. First of all, you pointed a lack of documentation regarding "backup & restore" Taiga. This is a very good point and we agree that we should improve this, specially for newcomers, as you mention.

On the other hand, your specific proposal does not fit very well with this repository. Bind mounts aren't better for creating backups and neither are good for newcomers, because bind-mounts are the not-recommended way according to docker official documentation. I think that we better offer the good practices and make them available to everyone (basically how to pg_dump the database and tar the media files).

This leads to the counter-proposal for this PR. What we'd like to add is documentation about backup and restore Taiga instances in https://docs.taiga.io which is the place for such technical topics. In the 30-min setup (in https://resources.taiga.io) we'd add links to this new section in the technical documentation.

So we've created [this issue](https://tree.taiga.io/project/taiga/issue/4542) and if you'd like to, we could assign you as a reviewer to check if the new documentation is good enough.

Meanwhile, I'm closing both PRs.

Again thanks for your help and showing a way to improve Taiga!

**Comment by nuokh** [comment]
Fair enough regarding the bind mount vs volume decision.

I would love to help reviewing the docs. I'll read up more on volumes to construct a working and tested step-by-step backup and restore process. Maybe rewriting my fork for volumes as a learning exercise for myself could get this todo off your plate entirely :-)

**Comment by yamila-moreno** [comment]
Hi @nuokh !

thanks for your offering; I'm more than happy to do this together.

The documentation would be in a different repository, taiga-doc (for technical documentation) instead of taiga-resources (for more general documentation).

In the issue I mentioned, I'm going to describe what we need with all the detail that I may, and from that point I can guide you through the PR and the needs. So I invite you to continue [here](https://tree.taiga.io/project/taiga/issue/4542). If you prefer, we can have this conversation in a github issue (in the proper repository).

**Comment by yamila-moreno** [comment]
check it here! as you have github user, we can follow better here: https://github.com/kaleidos-ventures/taiga-docker/issues/14

**Pull request closed without merging**
